const categories = {
  Marketing: [
    "Advertising",
    "Affiliate Marketing",
    "Analytics & Automation",
    "Branding",
    "Content Marketing",
    "Digital Marketing",
    "Growth Hacking",
    "Marketing Fundamentals",
    "Product Marketing",
    "Public Relations",
    "Search Engine Optimization",
    "Social Media Marketing",
    "Video & Mobile Marketing",
  ],
  "Personal Development": [
    "Personal Transformation",
    "Productivity",
    "Leadership",
    "Personal Finance",
    "Career Development",
    "Parenting & Relationships",
    "Happiness",
    "Religion & Spirituality",
    "Personal Brand Building",
    "Creativity",
    "Influence",
    "Self Esteem",
    "Stress Management",
    "Memory & Study Skills",
    "Motivation",
  ],
  Lifestyle: [
    "Arts & Crafts",
    "Food & Beverage",
    "Beauty & Makeup",
    "Travel",
    "Gaming",
    "Home Improvement",
    "Pet Care & Training",
  ],
  Photography: [
    "Digital Photography",
    "Photography Fundamentals",
    "Portraits",
    "Photography Tools",
    "Commercial Photography",
    "Video Design",
  ],
  "Health & Fitness": [
    "Fitness",
    "General Health",
    "Sports",
    "Nutrition",
    "Yoga",
    "Mental Health",
    "Dieting",
    "Self Defense",
    "Safety & First Aid",
    "Dance",
    "Meditation",
  ],
  Music: [
    "Instruments",
    "Production",
    "Music Fundamentals",
    "Vocal",
    "Music Techniques",
    "Music Software",
  ],
  Design: [
    "Web Design",
    "Graphic Design",
    "Development Tools",
    "User Experience",
    "Game Design",
    "Design Thinking",
    "3D & Animation",
    "Fashion",
    "Architectural Design",
    "Interior Design",
  ],
  Business: [
    "Finance",
    "Entrepreneurship",
    "Communications",
    "Management",
    "Sales",
    "Strategy",
    "Operations",
    "Project Management",
    "Business Law",
    "Data & Analytics",
    "Home Business",
    "Human Resources",
    "Industry",
    "Media",
    "Real Estate"
  ]
};

module.exports = { categories };
