module.exports = [
  "Entrepreneurship",
  "Home Business",
  "Media",
  "Web Design",
  "Graphic Design",
  "Development Tools",
  "Fashion",
  "Interior Design",
  "Fitness",
  "General Health",
  "Nutrition",
  "Mental Health",
  "Dieting",
  "Meditation",
  "Food & Beverage",
  "Beauty & Makeup",
  "Travel",
  "Home Improvement",
  "Advertising",
  "Affiliate Marketing",
  "Analytics & Automation",
  "Branding",
  "Content Marketing",
  "Digital Marketing",
  "Growth Hacking",
  "Marketing Fundamentals",
  "Product Marketing",
  "Public Relations",
  "Search Engine Optimization",
  "Social Media Marketing",
  "Video & Mobile Marketing",
  "Instruments",
  "Production",
  "Music Fundamentals",
  "Vocal",
  "Music Techniques",
  "Music Software",
  "Personal Transformation",
  "Productivity",
  "Leadership",
  "Personal Finance",
  "Career Development",
  "Parenting & Relationships",
  "Happiness",
  "Religion & Spirituality",
  "Personal Brand Building",
  "Creativity",
  "Influence",
  "Self Esteem",
  "Stress Management",
  "Memory & Study Skills",
  "Motivation",
  "Digital Photography",
  "Photography Fundamentals",
  "Portraits",
  "Photography Tools",
  "Commercial Photography",
  "Video Design",
];
